---

- name: Install Docker - Setting up Nodes
  become: yes
  hosts: all
  roles:
    - "install-docker-ubuntu"
    - "setting-up-nodes"
  tags: 
    - "setup"

- name: Clean Your Existing Kubernetes Configuration in Nodes     
  become: yes
  hosts: all
  roles:
    - "clean-up-config"
  tags: 
    - "clean"