kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "ingress-denots-web"
spec:
  rules:
    - host: filkom.example.net
      http:
        paths:
          - path: /
            backend:
              serviceName: denots-web-service
              servicePort: 3000